import streamlit as st
import streamlit.components.v1 as components
import os

st.set_page_config(page_title='Mon101 วัดพื้นที่', page_icon='📐', layout='wide')
APP=os.path.dirname(os.path.abspath(__file__))
logo=os.path.join(APP,'logo.jpg')
if os.path.exists(logo): st.image(logo,width=110)
st.title('📐 Mon101 วัดพื้นที่แปลงนา')
st.caption('ซูม/เลื่อนแผนที่ได้โดยไม่รีเฟรช • กากบาทกลางจอคือจุดที่จะปัก')

html=r'''<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"><style>
html,body,#map{margin:0;width:100%;height:100%;overflow:hidden}#map{height:680px}.tools{position:absolute;z-index:9999;top:10px;left:10px;display:flex;gap:6px;flex-wrap:wrap}button{border:0;border-radius:9px;padding:9px 11px;background:white;font-weight:700;box-shadow:0 2px 7px #555}#pin{background:#d71920;color:white}.info{position:absolute;z-index:9999;bottom:10px;left:10px;right:10px;max-width:460px;background:#fffffff2;padding:10px;border-radius:12px}.cross{position:absolute;z-index:9998;left:50%;top:50%;transform:translate(-50%,-50%);pointer-events:none;width:36px;height:36px}.cross:before,.cross:after{content:'';position:absolute;background:red}.cross:before{width:36px;height:3px;top:16px}.cross:after{height:36px;width:3px;left:16px}.small{font-size:12px;margin-top:5px}@media(max-width:600px){#map{height:650px}.info{font-size:13px}}
</style></head><body><div id="map"></div><div class="cross"></div><div class="tools"><button id="gps">📍 GPS</button><button id="sat">🛰️ ดาวเทียม</button><button id="road">🗺️ ถนน</button></div><div class="info"><b>📌 เลื่อนแผนที่ให้กากบาทตรงมุมแปลง</b><br><button id="pin">📌 ปักหมุด</button> <button id="undo">↩️ ลบล่าสุด</button> <button id="clear">🗑️ ใหม่</button> <button id="save">💾 บันทึก</button> <button id="export">📥 JSON</button><div id="msg" class="small"></div><div id="area" class="small"></div></div><script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script>
const PK='mon101_points_v5',RK='mon101_records_v5',VK='mon101_view_v5';let pts=JSON.parse(localStorage.getItem(PK)||'[]'),view=JSON.parse(localStorage.getItem(VK)||'null');let map=L.map('map').setView(view?[view.lat,view.lon]:[17.4138,102.7875],view?view.z:17);let sat=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:20,attribution:'Esri'}).addTo(map);let road=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'OSM'});let marks=[],shape=null;
function savePts(){localStorage.setItem(PK,JSON.stringify(pts))}function areaM2(a){if(a.length<3)return 0;let R=6378137,s=0;for(let i=0;i<a.length;i++){let p=a[i],q=a[(i+1)%a.length],x=p[1]*Math.PI/180,y=p[0]*Math.PI/180,u=q[1]*Math.PI/180,v=q[0]*Math.PI/180;s+=(u-x)*(2+Math.sin(y)+Math.sin(v))}return Math.abs(s*R*R/2)}function areaText(m){let r=Math.floor(m/1600),x=m-r*1600,n=Math.floor(x/400),w=(x-n*400)/4;return r.toLocaleString()+' ไร่ '+n.toLocaleString()+' งาน '+w.toFixed(2)+' ตารางวา'}function redraw(){marks.forEach(x=>map.removeLayer(x));marks=[];if(shape)map.removeLayer(shape);shape=null;pts.forEach((p,i)=>marks.push(L.marker(p).addTo(map).bindTooltip('จุด '+(i+1))));if(pts.length>=3)shape=L.polygon(pts,{color:'red',weight:3,fillColor:'#ffd400',fillOpacity:.25}).addTo(map);else if(pts.length==2)shape=L.polyline(pts,{color:'red',weight:3}).addTo(map);document.getElementById('msg').textContent='ปักแล้ว '+pts.length+' จุด';document.getElementById('area').textContent=pts.length>=3?'📐 '+areaText(areaM2(pts)):''}
map.on('moveend',()=>{let c=map.getCenter();localStorage.setItem(VK,JSON.stringify({lat:c.lat,lon:c.lng,z:map.getZoom()}))});document.getElementById('pin').onclick=()=>{let c=map.getCenter();pts.push([+c.lat.toFixed(8),+c.lng.toFixed(8)]);savePts();redraw()};document.getElementById('undo').onclick=()=>{pts.pop();savePts();redraw()};document.getElementById('clear').onclick=()=>{pts=[];savePts();redraw()};document.getElementById('save').onclick=()=>{if(pts.length<3){alert('ต้องมีอย่างน้อย 3 จุด');return}let r=JSON.parse(localStorage.getItem(RK)||'[]');r.push({date:new Date().toLocaleString('th-TH'),points:pts,area_m2:areaM2(pts),area:areaText(areaM2(pts))});localStorage.setItem(RK,JSON.stringify(r));alert('บันทึกแปลงแล้ว')};document.getElementById('export').onclick=()=>{let r=localStorage.getItem(RK)||'[]',b=new Blob([r],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='mon101_records.json';a.click()};document.getElementById('gps').onclick=()=>navigator.geolocation&&navigator.geolocation.getCurrentPosition(p=>map.setView([p.coords.latitude,p.coords.longitude],19),e=>alert('GPS: '+e.message),{enableHighAccuracy:true,timeout:15000,maximumAge:0});document.getElementById('sat').onclick=()=>{map.addLayer(sat);map.removeLayer(road)};document.getElementById('road').onclick=()=>{map.addLayer(road);map.removeLayer(sat)};redraw();
</script></body></html>'''
components.html(html,height=700,scrolling=False)

st.divider()
st.subheader('💰 ราคาค่าบริการ')
c1,c2,c3=st.columns(3)
c1.metric('🚜 ไถ','250 บาท/ไร่');c2.metric('⚙️ ปั่นดิน','350 บาท/ไร่');c3.metric('🚜⚙️ รวม','600 บาท/ไร่')
st.caption('ข้อมูลการบันทึกเก็บในเบราว์เซอร์เครื่องนี้ และดาวน์โหลด JSON สำรองได้')
